apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: default
spec: #공식문서에서 1.storageclassname 2.volumename 3.accessmode 4.resources있는 야멀파일 찾을 것
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: "" # 빈 문자열은 명시적으로 설정해야 하며 그렇지 않으면 기본 스토리지클래스가 설정됨
  volumeName: db-pv #이거 파드에 있는 볼륨이 아니라 pv이름으로 해야