apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: default
spec:
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteOnce
    claimRef:
      name: db-pvc
      namespace: default
    storageClassName: ""
    hostPath:                  # ✅ 볼륨 타입 명시 (로컬 테스트용)
      path: /var/lib/mysql